### ISSUE TITLE
Support `mobileRedirectB3`

### ISSUE THREAD

**Issue by romaninsh** [medsleuthinc/aws-whitelabel#8]
#### Issue Context: 
dev/prod, b3, https://github.com/medsleuthinc/infrastructure/issues/621

#### Description: 
A lambda is required to perform redirection from `survey.example.com` to `survey-b3.example.com`. The cloudfront distribution fro `survey` should have a trigger (lambda@edge), but only when option `mobileRedirectB3` is set for a subdomain.

``` yaml
  testclient.com:
      - name: survey
        service: b2-frontend
        mobileRedirectB3: true    # <<<<<<< - new option indicating redirect to $1-b3

      - name: survey-b3
        service: b3
```

#### Expected Results: 
Mobile users are redirected to `survey-b3` while others remain on `survey` subdomain.
